---
title: "Fitting Secondary Model"
author: "Jun Su"
date: "2023-03-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# set work directory
```{r}
setwd("C:/Users/sujun/Documents/GitHub/Bacillus-cereus-exposure-assessment-model/Re-fit")
```

# generate input file
```{r}
# import 22dC and 10dC growth parameters
data_22dC <- read.csv("OutputFiles/gp_22dC_new.csv")
data_22dC$T <- rep(22,34)
data_22dC_mumax <- data_22dC[,c("isolate","T","mumax")]
data_10dC <- read.csv("OutputFiles/gp_10dC_new.csv")
data_10dC$T <- rep(10,30)
data_10dC_mumax <- data_10dC[,c("isolate","T","mumax")]

# incorporate growth/no growth data 
isolate <- c(193,194,402,407,413,433,457,474,495,518,536,564,570,638,649,
             193,194,402,407,413,433,457,474,495,518,536,564,570,638,649)
T <- rep(8,30)
T[14]<-6
T[29]<-6
mumax <- rep(0,30)
df <- data.frame(isolate = isolate, T = T, mumax = mumax)

# combine data
data <- rbind(data_22dC_mumax,data_10dC_mumax,df)

# covert unit and calculate square root 
data$mumax_2 = data$mumax/2.303*24
data$sqrt_mumax_2 = sqrt(data$mumax_2)

# change column names
colnames(data) <- c("Isolate","T","mumax_ln_h","mumax_log10_day","sqrt_mumax_log10_day") 

# save file 
write.csv(data,"OutputFiles/mumax_new.csv")
```

# fit secondary model 
```{r}
# subset data by isolates
unique_isolates <- unique(data[c("Isolate")])

# initialize a list to store the fits  
b <- list()
Tmin <- list()

# loop over each isolate and rep combination to fit secondary model
for (i in 1:nrow(unique_isolates)) {
  isolate <- unique_isolates$Isolate[i]
  isolate_data <- subset(data, Isolate == isolate) # subset the data for the current isolate
  sqrt_mumax <- isolate_data$sqrt_mumax_log10_day
  fit <- lm(sqrt_mumax ~ isolate_data$T)
  b[isolate] <- coef(fit)[2]
  Tmin[isolate] <- -coef(fit)[1]/coef(fit)[2]
}
```

# generate output
```{r}
# create a data frame to store the results
results <- data.frame(
  Isolate = character(),
  Slope = numeric(),
  Tmin = numeric(),
  stringsAsFactors = FALSE
)

# loop over each isolate and add the results to the data frame
for (i in 1:nrow(unique_isolates)) {
  isolate <- unique_isolates$Isolate[i]
  slope <- b[[isolate]]
  tmin <- Tmin[[isolate]]
  results <- rbind(results, data.frame(Isolate = isolate, b = slope, Tmin = tmin))
}

# write the results to a CSV file
write.table(results, file = "OutputFiles/sec_model_new.csv", sep = ",", row.names = FALSE, quote = TRUE)
```

