---
title: "What-if scenarios"
author: "Jun Su"
date: "2023-12-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/sujun/Documents/GitHub/Bacillus-cereus-exposure-assessment-model")
```

# set environment
```{r}
# load packages 
library(tibble)
library(EnvStats)         # to load rtri function 
library(truncnorm)        # to load rtruncnorm function
library(jmuOutlier)       # to load rlaplace function
library(dplyr)
library(formula.tools)    # to load 'rhs'
library(purrr)            # to load 'map'
library(deSolve)          # to load 'ode'
library(rlang)

# load utility functions
source("Exposure assessment model/UtilityFunctions_dynamic_growth.R")

# set up dataframe for modeling 100 units of HTST milk 
n_sim = 100
data = data.frame(unit_id = rep(seq(1,n_sim)))
```

# scenario 1 - product delivery delay, w/o temperature abuse
```{r}
# set seed
set.seed(1)
# Stage 1: facility storage 
## (a)  Sample the temperature distribution
data$T_F <- rep(runif(n_sim,min=3.5,max=4.5)) #uniform distribution
## (b) Sample the storage time (in days) distribution
data$t_F <- rep(runif(n_sim,min=1,max=2)) #uniform distribution

# Stage 2: transport from facility to retail store
## (a)  Sample the temperature distribution
data$T_T <- rep(rtri(n_sim,min=1.7,max=10.0,mode=4.4)) #triangular distribution
## (b) Sample the transportation time (in days) distribution (delayed by 3 days)
data$t_T <- rep(rtri(n_sim,min=1+3,max=10+3,mode=5+3)) 

# Stage 3: storage/display at retail store
## (a)  Sample the temperature distribution
data$T_S <- rep(rtruncnorm(n_sim,a=-1.4,b=5.4,mean=2.3,sd=1.8)) #truncated normal distribution
## (b) Sample the storage time (in days) distribution
data$t_S <- rep(rtruncnorm(n_sim,a=0.042,b=10.0, mean=1.821,sd=3.3)) #truncated normal distribution

## Stage 4: transportation from retail store to home
## (a)  Sample the temperature distribution
data$T_T2 <- rep(rtruncnorm(n_sim,a=0,b=10,mean=8.5,sd=1.0)) #truncated normal distribution
## (b) Sample the transportation time (in days) distribution 
data$t_T2 <- rep(rtruncnorm(n_sim,a=0.01,b=0.24, mean=0.04,sd=0.02)) #truncated normal distribution

## Stage 5: home storage 
## (a)  Sample the temperature distribution
temps <- rep(NA, n_sim)
for (i in 1:n_sim){
  number <- rlaplace(1,m=4.06,s=2.31)
  while (number > 15 | number < -1) {
    number <- rlaplace(1,m=4.06,s=2.31) #truncated laplace distribution 
  }
  temps[i] <- number
}
data$T_H <- temps
## (b) Define t_H as 35 or 21 days for all units
# data$t_H <- rep(35, each = n_sim)
data$t_H <- rep(21, each = n_sim)
```

# scenario 2 - temperature abuse during retail - home transportation 
```{r}
# set seed
set.seed(1)
# Stage 1: facility storage 
## (a)  Sample the temperature distribution
data$T_F <- rep(runif(n_sim,min=3.5,max=4.5)) #uniform distribution
## (b) Sample the storage time (in days) distribution
data$t_F <- rep(runif(n_sim,min=1,max=2)) #uniform distribution

# Stage 2: transport from facility to retail store
## (a)  Sample the temperature distribution
data$T_T <- rep(rtri(n_sim,min=1.7,max=10.0,mode=4.4)) #triangular distribution
## (b) Sample the transportation time (in days) distribution
data$t_T <- rep(rtri(n_sim,min=1,max=10,mode=5)) #triangular distribution

# Stage 3: storage/display at retail store
## (a)  Sample the temperature distribution
data$T_S <- rep(rtruncnorm(n_sim,a=-1.4,b=5.4,mean=2.3,sd=1.8)) #truncated normal distribution
## (b) Sample the storage time (in days) distribution
data$t_S <- rep(rtruncnorm(n_sim,a=0.042,b=10.0, mean=1.821,sd=3.3)) #truncated normal distribution

## Stage 4: transportation from retail store to home
## (a)  Sample the temperature distribution, increase by 25C
data$T_T2 <- rep(rtruncnorm(n_sim,a=0+25,b=10+25,mean=8.5+25,sd=1.0)) #truncated normal distribution
## (b) Sample the transportation time (in days) distribution 
data$t_T2 <- rep(rtruncnorm(n_sim,a=0.01,b=0.24, mean=0.04,sd=0.02)) #truncated normal distribution

## Stage 5: home storage 
## (a)  Sample the temperature distribution
temps <- rep(NA, n_sim)
for (i in 1:n_sim){
  number <- rlaplace(1,m=4.06,s=2.31)
  while (number > 15 | number < -1) {
    number <- rlaplace(1,m=4.06,s=2.31) #truncated laplace distribution 
  }
  temps[i] <- number
}
data$T_H <- temps
## (b) Define t_H as 35 or 21 days for all units
# data$t_H <- rep(35, each = n_sim)
data$t_H <- rep(21, each = n_sim)
```

# Scenario 3 - home storage temperature abuse
```{r}
# set seed
set.seed(1)
# Stage 1: facility storage 
## (a)  Sample the temperature distribution
data$T_F <- rep(runif(n_sim,min=3.5,max=4.5)) #uniform distribution
## (b) Sample the storage time (in days) distribution
data$t_F <- rep(runif(n_sim,min=1,max=2)) #uniform distribution

# Stage 2: transport from facility to retail store
## (a)  Sample the temperature distribution
data$T_T <- rep(rtri(n_sim,min=1.7,max=10.0,mode=4.4)) #triangular distribution
## (b) Sample the transportation time (in days) distribution
data$t_T <- rep(rtri(n_sim,min=1,max=10,mode=5)) #triangular distribution

# Stage 3: storage/display at retail store
## (a)  Sample the temperature distribution
data$T_S <- rep(rtruncnorm(n_sim,a=-1.4,b=5.4,mean=2.3,sd=1.8)) #truncated normal distribution
## (b) Sample the storage time (in days) distribution
data$t_S <- rep(rtruncnorm(n_sim,a=0.042,b=10.0, mean=1.821,sd=3.3)) #truncated normal distribution

## Stage 4: transportation from retail store to home
## (a)  Sample the temperature distribution
data$T_T2 <- rep(rtruncnorm(n_sim,a=0,b=10,mean=8.5,sd=1.0)) #truncated normal distribution
## (b) Sample the transportation time (in days) distribution 
data$t_T2 <- rep(rtruncnorm(n_sim,a=0.01,b=0.24, mean=0.04,sd=0.02)) #truncated normal distribution

## Stage 5: home storage 
## (a)  Sample the temperature distribution, mean increase by 1C
temps <- rep(NA, n_sim)
 for (i in 1:n_sim){
   number <- rlaplace(1,m=4.06+1,s=2.31)
   while (number > 15+1 | number < -1+1) {
     number <- rlaplace(1,m=4.06+1,s=2.31) #truncated laplace distribution 
   }
   temps[i] <- number
 }
data$T_H <- temps
## (b) Define t_H as 35 or 21 days for all units
# data$t_H <- rep(35, each = n_sim)
data$t_H <- rep(21, each = n_sim)
```

# Scenario 4 - increase variability in home storage temperature 
```{r}
# set seed
set.seed(1)
## Stage 1: facility storage 
## (a)  Sample the temperature distribution
data$T_F <- rep(runif(n_sim,min=3.5,max=4.5)) #uniform distribution
## (b) Sample the storage time (in days) distribution
data$t_F <- rep(runif(n_sim,min=1,max=2)) #uniform distribution

# Stage 2: transport from facility to retail store
## (a)  Sample the temperature distribution
data$T_T <- rep(rtri(n_sim,min=1.7,max=10.0,mode=4.4)) #triangular distribution
## (b) Sample the transportation time (in days) distribution
data$t_T <- rep(rtri(n_sim,min=1,max=10,mode=5)) #triangular distribution

# Stage 3: storage/display at retail store
## (a)  Sample the temperature distribution
data$T_S <- rep(rtruncnorm(n_sim,a=-1.4,b=5.4,mean=2.3,sd=1.8)) #truncated normal distribution
## (b) Sample the storage time (in days) distribution
data$t_S <- rep(rtruncnorm(n_sim,a=0.042,b=10.0, mean=1.821,sd=3.3)) #truncated normal distribution

## Stage 4: transportation from retail store to home
## (a)  Sample the temperature distribution
data$T_T2 <- rep(rtruncnorm(n_sim,a=0,b=10,mean=8.5,sd=1.0)) #truncated normal distribution
## (b) Sample the transportation time (in days) distribution 
data$t_T2 <- rep(rtruncnorm(n_sim,a=0.01,b=0.24, mean=0.04,sd=0.02)) #truncated normal distribution

## Stage 5: home storage 
## (a)  Sample the temperature distribution, sd increase by 1C
temps <- rep(NA, n_sim)
for (i in 1:n_sim){
  number <- rlaplace(1,m=4.06,s=2.31+1)
  while (number > 15 | number < -1) {
    number <- rlaplace(1,m=4.06,s=2.31+1) #truncated laplace distribution 
  }
  temps[i] <- number
}
data$T_H <- temps
## (b) Define t_H as 35 or 21 days for all units
# data$t_H <- rep(35, each = n_sim)
data$t_H <- rep(21, each = n_sim)
```

## Model temperature profiles of 100 units HTST milk 
```{r}
env_cond_time <- matrix(c(rep(0,100),
                          data$t_F, 
                          data$t_F+0.001,
                          data$t_F + data$t_T,
                          data$t_F + data$t_T+0.001,
                          data$t_F + data$t_T + data$t_S,
                          data$t_F + data$t_T + data$t_S+0.001,
                          data$t_F + data$t_T + data$t_S + data$t_T2,
                          data$t_F + data$t_T + data$t_S + data$t_T2+0.001,
                          data$t_F + data$t_T + data$t_S + data$t_T2 + data$t_H), ncol = 10)

env_cond_temp <- matrix(c(data$T_F, 
                          data$T_F,
                          data$T_T,
                          data$T_T,
                          data$T_S,
                          data$T_S,
                          data$T_T2,
                          data$T_T2,
                          data$T_H,
                          data$T_H), ncol = 10)
```

# predict dynamic growth
```{r}
# Import data set
data_Q0 = read.csv("Exposure assessment model/InputFiles/Q0_h0_summary.csv")
data_Nmax = read.csv("Exposure assessment model/InputFiles/Nmax_new.csv")
data_sec_model = read.csv("Exposure assessment model/InputFiles/sec_model_new.csv")
Clade = c("I","II","VII","IV","IV","IV","IV","II","III","IV","II","VII","II","V","V","IV")
# Generate N0 from a Poisson distribution 
set.seed(42)
N0 = rpois(n = n_sim, lambda = 1e2*1900)
N0 = N0/1900

# Generate simulation input
# Input Q0
simulation_input <- data.frame(isolate = data_Q0$isolate, Q0 = data_Q0$Q0, 
                               Nmax = data_Nmax$average_Nmax, b = data_sec_model$Slope, 
                               Tmin = data_sec_model$Tmin,Clade)

simulation_input$Topt = sapply(simulation_input$Clade, xopt_func)
simulation_input$mu_opt = (simulation_input$b*(simulation_input$Topt-simulation_input$Tmin))^2 

# Run simulation
final_conc <- simulation_input %>%
  rowwise() %>%
  mutate(final_conc_isolate = list(lapply(1:n_sim, function(j) {
    my_primary <- list(mu_opt = mu_opt, Nmax = Nmax, N0 = N0[j], Q0 = Q0)
    sec_temperature <- list(model = "reducedRatkowsky", xmin = Tmin, b = b, clade = Clade)
    my_secondary <- list(temperature = sec_temperature)
    growth <- predict_dynamic_growth(times = env_cond_time[j,],
                                     env_conditions = tibble(time = env_cond_time[j,],
                                                             temperature = env_cond_temp[j,]),
                                     my_primary,
                                     my_secondary)
    sim <- growth$simulation
    return(tail(sim$logN, 1))
  }))) %>%
  pull(final_conc_isolate)

# Convert the list of 16 elements into a matrix
matrix <- t(sapply(final_conc, function(x) sapply(x, tail, n=1)))

# Calculate the percentage over 5 log for each row (element) in the matrix
percent_over_5 <- rowMeans(matrix > 5) * 100
```

# Generate output
```{r}
# scenario 1 d35
scenario_1_d35 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_1_d35) [1] <- "isolate"
colnames(scenario_1_d35) [2] <- "Group"
scenario_1_d35 <- as.data.frame (scenario_1_d35)
scenario_1_d35$day <- 35
scenario_1_d35$sc <- 1
scenario_1_d35 <- scenario_1_d35[order(scenario_1_d35$Group), ]

# scenario 1 d21
scenario_1_d21 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_1_d21) [1] <- "isolate"
colnames(scenario_1_d21) [2] <- "Group"
scenario_1_d21 <- as.data.frame (scenario_1_d21)
scenario_1_d21$day <- 21
scenario_1_d21$sc <- 1
scenario_1_d21 <- scenario_1_d21[order(scenario_1_d21$Group), ]

# scenario 2 d35
scenario_2_d35 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_2_d35) [1] <- "isolate"
colnames(scenario_2_d35) [2] <- "Group"
scenario_2_d35 <- as.data.frame (scenario_2_d35)
scenario_2_d35$day <- 35
scenario_2_d35$sc <- 2
scenario_2_d35 <- scenario_2_d35[order(scenario_2_d35$Group), ]

# scenario 2 d21
scenario_2_d21 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_2_d21) [1] <- "isolate"
colnames(scenario_2_d21) [2] <- "Group"
scenario_2_d21 <- as.data.frame (scenario_2_d21)
scenario_2_d21$day <- 21
scenario_2_d21$sc <- 2
scenario_2_d21 <- scenario_2_d21[order(scenario_2_d21$Group), ]

# scenario 3 d35
scenario_3_d35 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_3_d35) [1] <- "isolate"
colnames(scenario_3_d35) [2] <- "Group"
scenario_3_d35 <- as.data.frame (scenario_3_d35)
scenario_3_d35$day <- 35
scenario_3_d35$sc <- 3
scenario_3_d35 <- scenario_3_d35[order(scenario_3_d35$Group), ]

# scenario 3 d21
scenario_3_d21 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_3_d21) [1] <- "isolate"
colnames(scenario_3_d21) [2] <- "Group"
scenario_3_d21 <- as.data.frame (scenario_3_d21)
scenario_3_d21$day <- 21
scenario_3_d21$sc <- 3
scenario_3_d21 <- scenario_3_d21[order(scenario_3_d21$Group), ]

# scenario 4 d35
scenario_4_d35 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_4_d35) [1] <- "isolate"
colnames(scenario_4_d35) [2] <- "Group"
scenario_4_d35 <- as.data.frame (scenario_4_d35)
scenario_4_d35$day <- 35
scenario_4_d35$sc <- 4
scenario_4_d35 <- scenario_4_d35[order(scenario_4_d35$Group), ]

# scenario 4 d21
scenario_4_d21 <- cbind(simulation_input$isolate, simulation_input$Clade, percent_over_5)
colnames(scenario_4_d21) [1] <- "isolate"
colnames(scenario_4_d21) [2] <- "Group"
scenario_4_d21 <- as.data.frame (scenario_4_d21)
scenario_4_d21$day <- 21
scenario_4_d21$sc <- 4
scenario_4_d21 <- scenario_4_d21[order(scenario_4_d21$Group), ]

What_if_scenario_result <- rbind(scenario_1_d35, scenario_1_d21, scenario_2_d35, scenario_2_d21, scenario_3_d35, scenario_3_d21, scenario_4_d35, scenario_4_d21)
write.csv(What_if_scenario_result, "Exposure assessment model/OutputFiles/What_if_scenario_result.csv")
```

