---
title: "Fitting Primary Growth Model"
author: "Jun Su"
date: "2023-03-16"
output: pdf_document
---

```{r setup}
knitr::opts_knit$set(root.dir = "C:/Users/sujun/Documents/GitHub/Bacillus-cereus-exposure-assessment-model")
```

# set environment
```{r}
# load packages
library(nlsMicrobio)
library(minpack.lm)

# load primary growth models
source("Primary model/UtilityFunctions_baranyi.R")
```

# fit 22 dC growth data 
# import growth data set 
```{r}
# 22dC growth data 
data1 <-read.csv("Primary model/InputFiles/data_22_new.csv")

# create a list of data frames, one for each isolate and rep
data_list <- split(data1, list(data1$Isolate, data1$Rep))

# 22dC starting values
starting_values_22dC <-read.csv("Primary model/InputFiles/Starting values_22dC.csv")
```

# subset data and fit Baranyi model
```{r}
# initialize a list to store the fits
fit_list <- list()

# loop over each sample and its repetitions
for (i in 1:length(data_list)) {
  # subset the data for the current sample and rep
  sub_data <- data_list[[i]]
  
  # extract the sample and rep information
  isolate <- unique(sub_data$Isolate)
  rep <- unique(sub_data$Rep)
  
  # set the starting values for the current isolate and rep
  start_values <- c(LOG10N0 = starting_values_22dC$LOG10N0[i],
                    lag = starting_values_22dC$lag[i],
                    mumax = starting_values_22dC$mumax[i],
                    LOG10Nmax = starting_values_22dC$LOG10Nmax[i])
  
  # fit the Baranyi model to the subset of data
  fit <- nlsLM(LOG10N ~ baranyi_log10N(t,lag,mumax,LOG10N0,LOG10Nmax), data=sub_data,
               start = start_values, 
               lower = c(0,0,0,0))
  
  # extract the model coefficients
  coef_values <- coefficients(fit)
  
  # add the fit and its summary to the fit list
  fit_list[[i]] <- data.frame(isolate=isolate, rep=rep, 
                              LOG10N0 = coef_values["LOG10N0"],
                              lag = coef_values["lag"],
                              mumax = coef_values["mumax"],
                              LOG10Nmax = coef_values["LOG10Nmax"])
}
```

# combine data and generate output 
```{r}
# combine the fits into a single data frame
fits_22dC <- do.call(rbind, fit_list)

# replace mumax of Iso433 rep1 and rep2 with refitted data 
outliers <- read.csv("Primary model/InputFiles/Outliers refit.csv")
# see Primary Growth Model Fitting.R for how the samples are fitted 

fits_22dC[8,] <- subset(outliers,ï..isolate == "433" & rep == "rep1") # Iso433 rep1 @ 22dC
fits_22dC[25,] <- subset(outliers,ï..isolate == "433" & rep == "rep2")  # Iso433 rep2 @ 22dC

# generate output
write.csv(fits_22dC,"Primary model/OutputFiles/gp_22dC_new.csv")
```

# fit 10 dC growth data 
# import growth dataset 
```{r}
# 10dC growth data 
data2 <- read.csv("Primary model/InputFiles/data_10_new.csv")
colnames(data2) = c("t","Rep","LOG10N","Isolate")
data2$t = as.numeric(data2$t)
data2$LOG10N = as.numeric(data2$LOG10N)

# create a list of data frames, one for each isolate and rep
data_list <- split(data2, list(data2$Isolate, data2$Rep))

# starting values
starting_values_10dC <-read.csv("Primary model/InputFiles/Starting values_10dC.csv")
```

# subset data and fit Baranyi model
```{r}
# initialize a list to store the fits
fit_list <- list()

# loop over each sample and its repetitions
for (i in 1:length(data_list)) {
  # subset the data for the current sample and rep
  sub_data <- data_list[[i]]
  
  # extract the sample and rep information
  isolate <- unique(sub_data$Isolate)
  rep <- unique(sub_data$Rep)
  
  # set the starting values for the current isolate and rep
  start_values <- c(LOG10N0 = starting_values_10dC$LOG10N0[i],
                    lag = starting_values_10dC$lag[i],
                    mumax = starting_values_10dC$mumax[i],
                    LOG10Nmax = starting_values_10dC$LOG10Nmax[i])
  
  # fit the Baranyi model to the subset of data
  fit <- nlsLM(LOG10N ~ baranyi_log10N(t,lag,mumax,LOG10N0,LOG10Nmax), data=sub_data,
               start = start_values, 
               lower = c(0,0,0,0))
  
  # extract the model coefficients
  coef_values <- coefficients(fit)
  
  # add the fit and its summary to the fit list
  fit_list[[i]] <- data.frame(isolate=isolate, rep=rep, 
                              LOG10N0 = coef_values["LOG10N0"],
                              lag = coef_values["lag"],
                              mumax = coef_values["mumax"],
                              LOG10Nmax = coef_values["LOG10Nmax"])
}
```

# combine data and generate output 
```{r}
# combine the fits into a single data frame
fits_10dC <- do.call(rbind, fit_list)

# replace mumax of Iso413 rep1 with refitted data 
fits_10dC[5,] <- subset(outliers,ï..isolate == "413" & rep == "rep1")  # Iso413 rep1 @ 10dC

# generate output
write.csv(fits_10dC,"Primary model/OutputFiles/gp_10dC_new.csv")
```

